os: linux

language: go

go:
  - 1.14.x

services:
    - docker

script:
  # Test
  - go test -v

  # Build
  - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
  - docker build -f Dockerfile -t romaneso/myhello:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag romaneso/myhello:latest romaneso/myhello:$GIT_SHA
  - docker push romaneso/myhello:latest
  - docker push romaneso/myhello:$GIT_SHA